CSE-790
electricimp/AWSSNS pull request #4
Opened 2019-08-13 11:20 UTC by smittytone

See https://electricimp.atlassian.net/browse/CSE-790

I've updated the library with now-style comments, and I've taken the opportunity to recast the constants as enums (though this can be easily changed back, if you prefer).

The example and tests have likewise been modernised, so this is all worth a '-docs' update if you don't want to bump the library version because of the const/enum change.

I've updated the examples in the Read Me so they don't reference undeclared consts (which were actually from the test file).

2019-08-13 17:42 UTC, betzrhodes requested changes
Also can you confirm that all links and example code have been tested.

2019-08-13 17:42 UTC, betzrhodes commented on README.md
> +| --- | --- |
Shouldn't these be enums now?

2019-08-13 17:42 UTC, betzrhodes commented on README.md
>          // Handle an SES SubscriptionConfirmation request
typo in comment SES -> SNS

2019-08-13 17:42 UTC, betzrhodes commented on README.md
>  const AWS_SNS_URL               = "<YOUR_SNS_URL>";
AWS_SNS_URL is not used. All examples use AWS_SNS_TOPIC_ARN. Please verify that this the same, and if so updated constant to `const AWS_SNS_TOPIC_ARN = "YOUR_TOPIC_ARN_HERE";`

2019-08-13 17:42 UTC, betzrhodes commented on README.md
>      "TopicArn": "YOUR_TOPIC_ARN_HERE"
See comment re: updating constants in the constructor. This example should either use the constant defined in the constructor or should format the value in a similar way to the value of the constant's. 
```
const AWS_SNS_TOPIC_ARN = "< YOUR_TOPIC_ARN_HERE>";
local params = {
    "TopicArn": AWS_SNS_TOPIC_ARN
}
```
or 
```
local params = {
    "TopicArn": "< YOUR_TOPIC_ARN_HERE>"
}
```

2019-08-13 17:42 UTC, betzrhodes commented on README.md
>      "TopicArn": AWS_SNS_TOPIC_ARN
See previous topic arn comment

2019-08-13 17:42 UTC, betzrhodes commented on README.md
>      "Endpoint": http.agenturl()
see previous topic arn comment

2019-08-13 17:42 UTC, betzrhodes commented on README.md
> -    "SubscriptionArn": YOUR_SUBSCRIPTION_ARN
see previous topic arn comment

2019-08-14 09:54 UTC, smittytone commented on README.md
> +| --- | --- |
Yes. Fixed.

2019-08-14 13:29 UTC, smittytone commented
Testing and examples not done yet — wanted to make sure you were happy with what I was doing first.
Do we have an AWS account for testing purposes that I can use?

2019-08-14 19:05 UTC, betzrhodes commented
The changes look good - definitely moving in the right direction.

2019-08-14 19:14 UTC, betzrhodes approved these changes

2019-10-18 13:28 UTC, smittytone commented
@betzrhodes tests pass, so I think this one's good for release.

2019-10-18 23:28 UTC, merged